# Generated by Django 4.1.2 on 2022-10-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(default=True)),
                ('category', models.CharField(choices=[('None', 'None'), ('DVD', 'DVD'), ('Book', 'Book'), ('Furniture', 'Furniture')], default='None', max_length=100)),
                ('size', models.CharField(max_length=50)),
            ],
        ),
    ]
